#!/usr/bin/env python3
"""
Read Alvium frame timestamps under external trigger and report the measured
inter-frame interval + frame rate. Use this to verify the Teensy trigger fps.

The timestamp is generated by the CAMERA's own clock when it receives each
trigger edge, so the interval between consecutive frames is an independent
cross-check of the Teensy's commanded fps (two different oscillators agreeing).

Requires: the Vimba X SDK/runtime installed system-wide, plus the matching
          `vmbpy` wheel (ships inside the SDK — it is NOT on PyPI). See
          host/SETUP.md for the full Linux setup.

Examples:
    python3 read_timestamps.py                 # capture 100 frames
    python3 read_timestamps.py 200             # capture 200 frames
    python3 read_timestamps.py --list-lines    # show selectable trigger inputs
    python3 read_timestamps.py 200 --source Line1
    python3 read_timestamps.py 200 --csv run.csv
"""

import argparse
import sys


def load_vmbpy():
    """Import vmbpy into module globals, or exit with a helpful message.

    vmbpy loads the native VmbC library at import time; if the Vimba X runtime
    is not installed system-wide, this import fails. Deferred until after arg
    parsing so `--help` works without the SDK present.
    """
    try:
        from vmbpy import (VmbSystem, VmbFeatureError, VmbTimeout,
                           FrameStatus)
    except (ImportError, OSError) as exc:
        sys.exit(
            f"Could not load vmbpy ({exc}).\n"
            "  - Is the Vimba X SDK/runtime installed system-wide?\n"
            "  - Is the matching vmbpy wheel installed in this environment?\n"
            "See host/SETUP.md for the Linux install steps."
        )
    globals().update(VmbSystem=VmbSystem, VmbFeatureError=VmbFeatureError,
                     VmbTimeout=VmbTimeout, FrameStatus=FrameStatus)

# ---- Defaults (override on the command line) --------------------------------
DEFAULT_SOURCE   = 'Line0'   # non-isolated input pin wired to the Teensy TRIG_PIN
DEFAULT_FRAMES   = 100
FRAME_TIMEOUT_MS = 2000      # must exceed one trigger period (>91 ms @ 11 fps)
# -----------------------------------------------------------------------------


def parse_args():
    p = argparse.ArgumentParser(
        description="Measure Alvium inter-frame timing under external trigger.")
    p.add_argument('num_frames', nargs='?', type=int, default=DEFAULT_FRAMES,
                   help=f"frames to capture (default {DEFAULT_FRAMES})")
    p.add_argument('--source', default=DEFAULT_SOURCE,
                   help=f"TriggerSource line wired to TRIG_PIN "
                        f"(default {DEFAULT_SOURCE})")
    p.add_argument('--timeout-ms', type=int, default=FRAME_TIMEOUT_MS,
                   help=f"per-frame timeout, must exceed one trigger period "
                        f"(default {FRAME_TIMEOUT_MS})")
    p.add_argument('--csv', metavar='PATH',
                   help="also write per-frame timestamps to a CSV file")
    p.add_argument('--camera-id',
                   help="open this camera id/serial instead of auto-selecting "
                        "(needed if more than one real camera is present)")
    p.add_argument('--list-cameras', action='store_true',
                   help="list all detected cameras and exit")
    p.add_argument('--list-lines', action='store_true',
                   help="print the camera's selectable TriggerSource lines and exit")
    return p.parse_args()


def try_set(cam, name, value):
    """Set a feature if the model has it; otherwise skip quietly."""
    try:
        cam.get_feature_by_name(name).set(value)
        print(f"  {name} = {value}")
        return True
    except (VmbFeatureError, AttributeError):
        print(f"  {name}: not available (skipped)")
        return False


def try_run(cam, *names):
    """Run the first command feature that exists (name varies by model/TL)."""
    for name in names:
        try:
            cam.get_feature_by_name(name).run()
            print(f"  ran {name}")
            return
        except (VmbFeatureError, AttributeError):
            continue
    print(f"  none of {names} available (timestamp not reset)")


def enum_entries(cam, name):
    """Available entries of an enum feature as plain strings ([] if absent)."""
    try:
        feat = cam.get_feature_by_name(name)
        return [str(e) for e in feat.get_available_entries()]
    except (VmbFeatureError, AttributeError):
        return []


def list_lines(cam):
    """Print the TriggerSource options so you can pick the wired input."""
    print(f"Camera: {cam.get_id()}")
    sources = enum_entries(cam, 'TriggerSource')
    if sources:
        print("Selectable TriggerSource values:")
        for s in sources:
            print(f"  {s}")
    else:
        print("TriggerSource enum not readable on this model.")
    lines = enum_entries(cam, 'LineSelector')
    if lines:
        print("Selectable LineSelector (physical I/O) values:")
        for ln in lines:
            print(f"  {ln}")


def is_simulator(cam):
    """True for the GenTL Camera Simulator transport-layer devices."""
    return 'Simulator' in (cam.get_model() or '')


def describe(cam):
    return f"{cam.get_id()}  {cam.get_model()}  (serial {cam.get_serial()})"


def select_camera(cams, camera_id):
    """Pick the camera to use: explicit id wins; else the sole real (non-sim) one."""
    if camera_id:
        for c in cams:
            if camera_id in (c.get_id(), c.get_serial()):
                return c
        sys.exit(f"Camera id/serial '{camera_id}' not found. "
                 f"Use --list-cameras to see options.")
    real = [c for c in cams if not is_simulator(c)]
    if len(real) == 1:
        return real[0]
    if not real:
        sys.exit("Only simulator cameras detected — no real Alvium found. "
                 "Check USB connection/power. Use --list-cameras to inspect.")
    ids = ', '.join(c.get_id() for c in real)
    sys.exit(f"Multiple real cameras detected ({ids}). "
             f"Pick one with --camera-id <id-or-serial>.")


def timestamp_hz(cam):
    """Ticks-per-second for the frame timestamp. USB3 Alvium reports ns (1 GHz)."""
    for name in ('DeviceTimestampFrequency', 'GevTimestampTickFrequency'):
        try:
            return float(cam.get_feature_by_name(name).get())
        except (VmbFeatureError, AttributeError):
            continue
    return 1e9  # U3V default: timestamp is already in nanoseconds


def configure_trigger(cam, source):
    print("Configuring external trigger (FrameStart / Timed):")
    try_set(cam, 'AcquisitionMode',   'Continuous')
    try_set(cam, 'TriggerSelector',   'FrameStart')
    if not try_set(cam, 'TriggerSource', source):
        avail = enum_entries(cam, 'TriggerSource')
        if avail:
            print(f"  -> available sources: {', '.join(avail)}")
            print("     re-run with --source <one of the above>")
    try_set(cam, 'TriggerActivation', 'RisingEdge')
    try_set(cam, 'ExposureMode',      'Timed')
    try_set(cam, 'TriggerMode',       'On')      # enable last


def capture(cam, num_frames, timeout_ms, csv_path):
    print("Resetting camera timestamp clock:")
    try_run(cam, 'TimestampReset', 'GevTimestampControlReset')

    hz = timestamp_hz(cam)
    print(f"Timestamp tick rate: {hz:.0f} Hz  ({1e9 / hz:.3f} ns/tick)")
    print(f"\nCapturing {num_frames} frames (Ctrl-C to stop early)...\n")

    csv_file = open(csv_path, 'w') if csv_path else None
    if csv_file:
        csv_file.write("frame_id,timestamp_ticks,dt_s,status\n")

    prev = None
    deltas = []
    incomplete = 0
    try:
        for frame in cam.get_frame_generator(limit=num_frames,
                                             timeout_ms=timeout_ms):
            ts = frame.get_timestamp()               # camera clock ticks
            ok = frame.get_status() == FrameStatus.Complete
            if not ok:
                incomplete += 1
            dt_s = (ts - prev) / hz if prev is not None else None
            if dt_s is not None:
                deltas.append(dt_s)
                print(f"frame {frame.get_id():>5}  ts={ts:>16}  "
                      f"dt={dt_s * 1e3:9.4f} ms  ({1.0 / dt_s:8.4f} Hz)"
                      f"{'' if ok else '   [INCOMPLETE]'}")
            else:
                print(f"frame {frame.get_id():>5}  ts={ts:>16}   (first)")
            if csv_file:
                status = 'Complete' if ok else str(frame.get_status())
                csv_file.write(f"{frame.get_id()},{ts},"
                               f"{'' if dt_s is None else dt_s},{status}\n")
            prev = ts
    except KeyboardInterrupt:
        print("\n(stopped early)")
    except VmbTimeout:
        print(f"\nTimed out waiting for a frame (>{timeout_ms} ms). "
              "Are triggers arriving? Check wiring, shared ground, and that "
              "the Teensy is running (serial heartbeat at 115200).")
    finally:
        if csv_file:
            csv_file.close()
            print(f"\nwrote {csv_path}")

    summarize(deltas, incomplete)


def summarize(deltas, incomplete):
    if not deltas:
        print("\nNo intervals measured — did any triggers arrive? "
              "Check wiring, shared ground, and that the Teensy is running.")
        return
    n = len(deltas)
    mean = sum(deltas) / n
    std = (sum((d - mean) ** 2 for d in deltas) / n) ** 0.5
    p2p = max(deltas) - min(deltas)
    print("\n---- summary ----")
    print(f"frames measured : {n + 1}")
    print(f"mean interval   : {mean * 1e3:.5f} ms")
    print(f"measured fps    : {1.0 / mean:.5f} Hz")
    print(f"interval std dev: {std * 1e6:.2f} us   (trigger jitter)")
    print(f"peak-to-peak    : {p2p * 1e6:.2f} us")
    if incomplete:
        print(f"incomplete frames: {incomplete}   (dropped/partial transfers)")


def main():
    args = parse_args()
    load_vmbpy()
    with VmbSystem.get_instance() as vmb:
        cams = vmb.get_all_cameras()
        if not cams:
            sys.exit("No camera found. Is the Alvium connected and powered, "
                     "and are USB permissions set up? See host/SETUP.md.")
        if args.list_cameras:
            print(f"{len(cams)} camera(s) detected:")
            for c in cams:
                tag = ' [simulator]' if is_simulator(c) else ''
                print(f"  {describe(c)}{tag}")
            return
        cam = select_camera(cams, args.camera_id)
        with cam:
            if args.list_lines:
                list_lines(cam)
                return
            print(f"Camera: {describe(cam)}")
            configure_trigger(cam, args.source)
            capture(cam, args.num_frames, args.timeout_ms, args.csv)


if __name__ == '__main__':
    main()
