#!/usr/bin/env python3
"""
Read Alvium frame timestamps under external trigger and report the measured
inter-frame interval + frame rate. Use this to verify the Teensy trigger fps.

The timestamp is generated by the CAMERA's own clock when it receives each
trigger edge, so the interval between consecutive frames is an independent
cross-check of the Teensy's commanded fps (two different oscillators agreeing).

Requires: pip install vmbpy      (Vimba X SDK + its transport layers installed)
Run:      python3 read_timestamps.py [num_frames]
"""

import sys
from vmbpy import VmbSystem, VmbFeatureError, FrameStatus

# ---- Match these to your rig ------------------------------------------------
TRIGGER_SOURCE   = 'Line0'   # non-isolated input pin wired to the Teensy TRIG_PIN
NUM_FRAMES       = int(sys.argv[1]) if len(sys.argv) > 1 else 100
FRAME_TIMEOUT_MS = 2000      # must exceed one trigger period (>91 ms @ 11 fps)
# -----------------------------------------------------------------------------


def try_set(cam, name, value):
    """Set a feature if the model has it; otherwise skip quietly."""
    try:
        cam.get_feature_by_name(name).set(value)
        print(f"  {name} = {value}")
    except (VmbFeatureError, AttributeError):
        print(f"  {name}: not available (skipped)")


def try_run(cam, *names):
    """Run the first command feature that exists (name varies by model/TL)."""
    for name in names:
        try:
            cam.get_feature_by_name(name).run()
            print(f"  ran {name}")
            return
        except (VmbFeatureError, AttributeError):
            continue
    print(f"  none of {names} available (timestamp not reset)")


def timestamp_hz(cam):
    """Ticks-per-second for the frame timestamp. USB3 Alvium reports ns (1 GHz)."""
    for name in ('DeviceTimestampFrequency', 'GevTimestampTickFrequency'):
        try:
            return float(cam.get_feature_by_name(name).get())
        except (VmbFeatureError, AttributeError):
            continue
    return 1e9  # U3V default: timestamp is already in nanoseconds


def main():
    with VmbSystem.get_instance() as vmb:
        cams = vmb.get_all_cameras()
        if not cams:
            sys.exit("No camera found.")
        with cams[0] as cam:
            print(f"Camera: {cam.get_id()}")

            print("Configuring external trigger (FrameStart / Timed):")
            try_set(cam, 'AcquisitionMode',   'Continuous')
            try_set(cam, 'TriggerSelector',   'FrameStart')
            try_set(cam, 'TriggerSource',     TRIGGER_SOURCE)
            try_set(cam, 'TriggerActivation', 'RisingEdge')
            try_set(cam, 'ExposureMode',      'Timed')
            try_set(cam, 'TriggerMode',       'On')      # enable last

            print("Resetting camera timestamp clock:")
            try_run(cam, 'TimestampReset', 'GevTimestampControlReset')

            hz = timestamp_hz(cam)
            print(f"Timestamp tick rate: {hz:.0f} Hz  ({1e9 / hz:.3f} ns/tick)")
            print(f"\nCapturing {NUM_FRAMES} frames "
                  f"(Ctrl-C to stop early)...\n")

            prev = None
            deltas = []
            for frame in cam.get_frame_generator(limit=NUM_FRAMES,
                                                  timeout_ms=FRAME_TIMEOUT_MS):
                ts = frame.get_timestamp()               # camera clock ticks
                ok = frame.get_status() == FrameStatus.Complete
                if prev is not None:
                    dt_s = (ts - prev) / hz
                    deltas.append(dt_s)
                    print(f"frame {frame.get_id():>5}  ts={ts:>16}  "
                          f"dt={dt_s * 1e3:9.4f} ms  ({1.0 / dt_s:8.4f} Hz)"
                          f"{'' if ok else '   [INCOMPLETE]'}")
                else:
                    print(f"frame {frame.get_id():>5}  ts={ts:>16}   (first)")
                prev = ts

            if deltas:
                n = len(deltas)
                mean = sum(deltas) / n
                std = (sum((d - mean) ** 2 for d in deltas) / n) ** 0.5
                p2p = max(deltas) - min(deltas)
                print("\n---- summary ----")
                print(f"frames measured : {n + 1}")
                print(f"mean interval   : {mean * 1e3:.5f} ms")
                print(f"measured fps    : {1.0 / mean:.5f} Hz")
                print(f"interval std dev: {std * 1e6:.2f} us   (trigger jitter)")
                print(f"peak-to-peak    : {p2p * 1e6:.2f} us")


if __name__ == '__main__':
    main()
